FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/ApiAluno/ApiAluno.csproj", "."]
RUN dotnet restore "./ApiAluno.csproj"
COPY . .

RUN dotnet build "./ApiAluno.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./ApiAluno.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "ApiAluno.dll"]